name: sync2gitee

on: 
  #push
  schedule:
    - cron:  '0 15 * * *'

jobs:
  repo-sync:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/wang1212
          dst: gitee/i_wang1212
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          black_list: "sync2gitee,font-glyphs,canvg,WebODM,exceljs,awesome-satellite-imagery-datasets,bubble-wrap,mapboxgl-vector-tiles"
          force_update: true
          timeout: '1h'
          debug: true
